/**
 * Hand-written fallback list, used when GOOGLE_PLACES_API_KEY is missing.
 *
 * These are all real restaurants inside the Grand Central → Stuytown corridor.
 * Coordinates are approximate (block-level) and the ratings / review counts are
 * ballpark figures typed by hand, NOT live Google data — run
 * `npm run fetch-restaurants` with an API key to replace them with the real thing.
 * Hours are deliberately left null so the "open at 7pm" filter stays out of the
 * way rather than guessing.
 */
import type { Cuisine } from '../src/types.ts'

export interface SeedRestaurant {
  place_id: string
  name: string
  address: string
  lat: number
  lng: number
  rating: number
  review_count: number
  price_level: number | null
  cuisine: Cuisine
  types: string[]
}

export const SEED_RESTAURANTS: SeedRestaurant[] = [
  {
    place_id: 'seed-grand-central-oyster-bar',
    name: 'Grand Central Oyster Bar & Restaurant',
    address: '89 E 42nd St (Lower Level), New York, NY 10017',
    lat: 40.7527,
    lng: -73.9772,
    rating: 4.3,
    review_count: 8600,
    price_level: 3,
    cuisine: 'Seafood',
    types: ['restaurant', 'seafood_restaurant', 'oyster bar', 'bar', 'classic'],
  },
  {
    place_id: 'seed-sakagura',
    name: 'Sakagura',
    address: '211 E 43rd St (basement), New York, NY 10017',
    lat: 40.7509,
    lng: -73.9718,
    rating: 4.5,
    review_count: 1900,
    price_level: 3,
    cuisine: 'Japanese',
    types: ['restaurant', 'japanese_restaurant', 'izakaya', 'sake bar', 'bar'],
  },
  {
    place_id: 'seed-aburiya-kinnosuke',
    name: 'Aburiya Kinnosuke',
    address: '213 E 45th St, New York, NY 10017',
    lat: 40.7522,
    lng: -73.9723,
    rating: 4.5,
    review_count: 1400,
    price_level: 3,
    cuisine: 'Japanese',
    types: ['restaurant', 'japanese_restaurant', 'izakaya', 'robata', 'bar'],
  },
  {
    place_id: 'seed-docks-oyster-bar',
    name: 'Docks Oyster Bar',
    address: '633 3rd Ave, New York, NY 10017',
    lat: 40.7494,
    lng: -73.974,
    rating: 4.2,
    review_count: 1500,
    price_level: 3,
    cuisine: 'Seafood',
    types: ['restaurant', 'seafood_restaurant', 'oyster bar', 'bar'],
  },
  {
    place_id: 'seed-kajitsu',
    name: 'Kajitsu',
    address: '125 E 39th St, New York, NY 10016',
    lat: 40.7492,
    lng: -73.977,
    rating: 4.6,
    review_count: 520,
    price_level: 4,
    cuisine: 'Vegetarian',
    types: ['restaurant', 'japanese_restaurant', 'vegetarian_restaurant', 'tasting menu', 'fine dining'],
  },
  {
    place_id: 'seed-le-parisien-bistrot',
    name: 'Le Parisien Bistrot',
    address: '163 E 33rd St, New York, NY 10016',
    lat: 40.7455,
    lng: -73.9787,
    rating: 4.5,
    review_count: 1200,
    price_level: 2,
    cuisine: 'French',
    types: ['restaurant', 'french_restaurant', 'bistro', 'cozy', 'wine'],
  },
  {
    place_id: 'seed-keens-steakhouse',
    name: 'Keens Steakhouse',
    address: '72 W 36th St, New York, NY 10018',
    lat: 40.7513,
    lng: -73.9861,
    rating: 4.6,
    review_count: 6900,
    price_level: 4,
    cuisine: 'Steak',
    types: ['restaurant', 'steak_house', 'bar', 'classic', 'historic', 'whiskey'],
  },
  {
    place_id: 'seed-cafe-china',
    name: 'Cafe China',
    address: '59 W 37th St, New York, NY 10018',
    lat: 40.7513,
    lng: -73.9853,
    rating: 4.4,
    review_count: 2400,
    price_level: 2,
    cuisine: 'Chinese',
    types: ['restaurant', 'chinese_restaurant', 'sichuan', 'cozy'],
  },
  {
    place_id: 'seed-her-name-is-han',
    name: 'Her Name Is Han',
    address: '17 E 31st St, New York, NY 10016',
    lat: 40.7461,
    lng: -73.9846,
    rating: 4.5,
    review_count: 2300,
    price_level: 2,
    cuisine: 'Korean',
    types: ['restaurant', 'korean_restaurant', 'cozy', 'soju', 'bar'],
  },
  {
    place_id: 'seed-jongro-bbq',
    name: 'Jongro BBQ',
    address: '22 W 32nd St, 2nd Floor, New York, NY 10001',
    lat: 40.7479,
    lng: -73.9877,
    rating: 4.4,
    review_count: 4600,
    price_level: 3,
    cuisine: 'Korean',
    types: ['restaurant', 'korean_restaurant', 'barbecue', 'grill', 'lively'],
  },
  {
    place_id: 'seed-ravagh-persian-grill',
    name: 'Ravagh Persian Grill',
    address: '11 E 30th St, New York, NY 10016',
    lat: 40.7455,
    lng: -73.9852,
    rating: 4.4,
    review_count: 1600,
    price_level: 2,
    cuisine: 'Mediterranean',
    types: ['restaurant', 'persian_restaurant', 'middle_eastern_restaurant', 'grill'],
  },
  {
    place_id: 'seed-marta',
    name: 'Marta',
    address: '29 E 29th St, New York, NY 10016',
    lat: 40.7449,
    lng: -73.9843,
    rating: 4.4,
    review_count: 2700,
    price_level: 3,
    cuisine: 'Pizza',
    types: ['restaurant', 'pizza_restaurant', 'italian_restaurant', 'bar', 'lively', 'trendy'],
  },
  {
    place_id: 'seed-eleven-madison-park',
    name: 'Eleven Madison Park',
    address: '11 Madison Ave, New York, NY 10010',
    lat: 40.7416,
    lng: -73.9872,
    rating: 4.6,
    review_count: 4300,
    price_level: 4,
    cuisine: 'Vegetarian',
    types: ['restaurant', 'fine_dining', 'vegetarian_restaurant', 'tasting menu', 'trendy'],
  },
  {
    place_id: 'seed-bhatti-indian-grill',
    name: 'Bhatti Indian Grill',
    address: '100 Lexington Ave, New York, NY 10016',
    lat: 40.743,
    lng: -73.9823,
    rating: 4.3,
    review_count: 1900,
    price_level: 2,
    cuisine: 'Indian',
    types: ['restaurant', 'indian_restaurant', 'grill', 'curry hill'],
  },
  {
    place_id: 'seed-pippali',
    name: 'Pippali',
    address: '129 E 27th St, New York, NY 10016',
    lat: 40.7423,
    lng: -73.9825,
    rating: 4.4,
    review_count: 1100,
    price_level: 2,
    cuisine: 'Indian',
    types: ['restaurant', 'indian_restaurant', 'cozy', 'curry hill'],
  },
  {
    place_id: 'seed-i-trulli',
    name: 'I Trulli',
    address: '122 E 27th St, New York, NY 10016',
    lat: 40.742,
    lng: -73.9834,
    rating: 4.4,
    review_count: 900,
    price_level: 3,
    cuisine: 'Italian',
    types: ['restaurant', 'italian_restaurant', 'wine bar', 'cozy', 'garden'],
  },
  {
    place_id: 'seed-blue-smoke',
    name: 'Blue Smoke',
    address: '116 E 27th St, New York, NY 10016',
    lat: 40.7419,
    lng: -73.984,
    rating: 4.3,
    review_count: 3400,
    price_level: 2,
    cuisine: 'American',
    types: ['restaurant', 'barbecue_restaurant', 'bar', 'lively', 'casual'],
  },
  {
    place_id: 'seed-flatiron-room',
    name: 'The Flatiron Room',
    address: '37 W 26th St, New York, NY 10010',
    lat: 40.7448,
    lng: -73.9895,
    rating: 4.5,
    review_count: 2600,
    price_level: 3,
    cuisine: 'American',
    types: ['bar', 'cocktail bar', 'whiskey', 'restaurant', 'live music', 'lively'],
  },
  {
    place_id: 'seed-upland',
    name: 'Upland',
    address: '345 Park Ave S, New York, NY 10010',
    lat: 40.7396,
    lng: -73.9846,
    rating: 4.5,
    review_count: 2900,
    price_level: 3,
    cuisine: 'American',
    types: ['restaurant', 'californian', 'bar', 'trendy', 'lively'],
  },
  {
    place_id: 'seed-rezdora',
    name: 'Rezdôra',
    address: '27 E 20th St, New York, NY 10003',
    lat: 40.7391,
    lng: -73.9884,
    rating: 4.6,
    review_count: 2000,
    price_level: 3,
    cuisine: 'Italian',
    types: ['restaurant', 'italian_restaurant', 'pasta', 'trendy', 'wine'],
  },
  {
    place_id: 'seed-cosme',
    name: 'Cosme',
    address: '35 E 21st St, New York, NY 10010',
    lat: 40.7392,
    lng: -73.988,
    rating: 4.5,
    review_count: 3000,
    price_level: 4,
    cuisine: 'Mexican',
    types: ['restaurant', 'mexican_restaurant', 'bar', 'trendy', 'cocktails'],
  },
  {
    place_id: 'seed-gramercy-tavern',
    name: 'Gramercy Tavern',
    address: '42 E 20th St, New York, NY 10003',
    lat: 40.7385,
    lng: -73.9882,
    rating: 4.6,
    review_count: 5700,
    price_level: 4,
    cuisine: 'American',
    types: ['restaurant', 'fine_dining', 'tavern', 'bar', 'classic'],
  },
  {
    place_id: 'seed-thai-villa',
    name: 'Thai Villa',
    address: '5 E 19th St, New York, NY 10003',
    lat: 40.7381,
    lng: -73.9895,
    rating: 4.5,
    review_count: 2400,
    price_level: 2,
    cuisine: 'Thai',
    types: ['restaurant', 'thai_restaurant', 'trendy', 'cocktails'],
  },
  {
    place_id: 'seed-sarashina-horii',
    name: 'Sarashina Horii',
    address: '41 E 20th St, New York, NY 10003',
    lat: 40.7387,
    lng: -73.9883,
    rating: 4.4,
    review_count: 800,
    price_level: 3,
    cuisine: 'Japanese',
    types: ['restaurant', 'japanese_restaurant', 'soba', 'noodle', 'quiet'],
  },
  {
    place_id: 'seed-nur',
    name: 'Nur',
    address: '34 E 20th St, New York, NY 10003',
    lat: 40.739,
    lng: -73.9883,
    rating: 4.5,
    review_count: 650,
    price_level: 4,
    cuisine: 'Mediterranean',
    types: ['restaurant', 'middle_eastern_restaurant', 'israeli', 'trendy', 'bar'],
  },
  {
    place_id: 'seed-barbounia',
    name: 'Barbounia',
    address: '250 Park Ave S, New York, NY 10003',
    lat: 40.7379,
    lng: -73.9861,
    rating: 4.4,
    review_count: 2200,
    price_level: 3,
    cuisine: 'Mediterranean',
    types: ['restaurant', 'mediterranean_restaurant', 'bar', 'lively', 'brunch'],
  },
  {
    place_id: 'seed-novita',
    name: 'Novitá',
    address: '102 E 22nd St, New York, NY 10010',
    lat: 40.7382,
    lng: -73.9853,
    rating: 4.5,
    review_count: 750,
    price_level: 3,
    cuisine: 'Italian',
    types: ['restaurant', 'italian_restaurant', 'cozy', 'neighborhood', 'wine'],
  },
  {
    place_id: 'seed-casa-mono',
    name: 'Casa Mono',
    address: '52 Irving Pl, New York, NY 10003',
    lat: 40.7357,
    lng: -73.9866,
    rating: 4.5,
    review_count: 1700,
    price_level: 3,
    cuisine: 'Mediterranean',
    types: ['restaurant', 'spanish_restaurant', 'tapas', 'wine bar', 'cozy', 'counter'],
  },
  {
    place_id: 'seed-dear-irving',
    name: 'Dear Irving',
    address: '55 Irving Pl, New York, NY 10003',
    lat: 40.7355,
    lng: -73.9866,
    rating: 4.5,
    review_count: 950,
    price_level: 3,
    cuisine: 'American',
    types: ['bar', 'cocktail bar', 'lounge', 'cozy', 'small plates'],
  },
  {
    place_id: 'seed-petes-tavern',
    name: "Pete's Tavern",
    address: '129 E 18th St, New York, NY 10003',
    lat: 40.7357,
    lng: -73.9862,
    rating: 4.3,
    review_count: 5000,
    price_level: 2,
    cuisine: 'American',
    types: ['restaurant', 'tavern', 'bar', 'pub', 'classic', 'historic', 'lively'],
  },
  {
    place_id: 'seed-el-parador-cafe',
    name: 'El Parador Cafe',
    address: '325 E 34th St, New York, NY 10016',
    lat: 40.744,
    lng: -73.9742,
    rating: 4.4,
    review_count: 1400,
    price_level: 3,
    cuisine: 'Mexican',
    types: ['restaurant', 'mexican_restaurant', 'classic', 'cozy', 'margaritas', 'bar'],
  },
  {
    place_id: 'seed-han-dynasty',
    name: 'Han Dynasty',
    address: '90 3rd Ave, New York, NY 10003',
    lat: 40.7322,
    lng: -73.9878,
    rating: 4.4,
    review_count: 2100,
    price_level: 2,
    cuisine: 'Chinese',
    types: ['restaurant', 'chinese_restaurant', 'sichuan', 'spicy', 'casual', 'lively'],
  },
  {
    place_id: 'seed-motorino',
    name: 'Motorino',
    address: '349 E 12th St, New York, NY 10003',
    lat: 40.7305,
    lng: -73.9836,
    rating: 4.4,
    review_count: 1600,
    price_level: 2,
    cuisine: 'Pizza',
    types: ['restaurant', 'pizza_restaurant', 'neapolitan', 'casual', 'counter', 'quick'],
  },
]
